### ISSUE TITLE
Settings --> LDP labels do not translate when a non-American English locale is chosen

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#11]
This issue has been moved from https://issues.folio.org/browse/LDPQURY-49

Overview: The LDP settings names are not translatable when a different language is chosen.

Steps to Reproduce:

1. Log into some FOLIO environment as a user with appropriate permissions to Settings
2. Go to Settings --> Developer and change the session locale to a locale other than American English

Expected Results: All settings names appear in the new locale name.

Actual Results: The names aren't correct. See attached screenshot.

![image-2021-02-10-10-24-35-124](https://user-images.githubusercontent.com/246609/107532630-17927600-6b8c-11eb-87d7-62e62507b28b.png)

**Comment by rjruizes** [comment]
Fixed in https://github.com/library-data-platform/ui-ldp/commit/e1488d7ee39694396beb3dd8ebc4ba93ad618d7f
