### ISSUE TITLE
Add setting to limit number of results displayed and retrieved

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#13]
Implement a fixed maximum for (L1) the number of results that will be displayed in the UI and (L2) the number of results that will be retrieved and can be exported using the export button.  L1 should be reasonably consistent with FOLIO UX conventions but taking into account that we do not currently support paging of results.  L2 should default to 1,000 and should be configurable (no lower than 1,000) by the FOLIO system administrator or via standard FOLIO configuration.

**Comment by MikeTaylor** [comment]
I'm moving the last part of this to its own issue.

**Comment by MikeTaylor** [comment]
Complete.
