### ISSUE TITLE
Add option to specify at query time how many results to retrieve

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#14]
Add an option allowing the user to specify, via drop-down box, the maximum number results to retrieve.  The choices in the drop-down list should start at 10 and increase by 10X, with the largest choice being the value of L2 as described in: https://github.com/library-data-platform/ui-ldp/issues/13

**Comment by MikeTaylor** [comment]
This was closed prematurely: the option works, but at present you just type in a number. It doesn't work the way the description specifies, with the exponential list of options.

**Comment by MikeTaylor** [comment]
... and we're done.
