### ISSUE TITLE
Add support for configuration of available schemas

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#16]
Allow schemas included in the drop-down box to be configurable by the FOLIO system administrator or via standard FOLIO configuration.

**Comment by MikeTaylor** [comment]
At present the list of schemas included in the dropdown box is obtained from the back-end web service: surely this is how we want it? Or do you mean that you want the ability to restrict the available set to a configured subset?

**Comment by nassibnassar** [comment]
What I had in mind was the need (1) to restrict the available set as well as (2) to add locally-created schemas (not created by LDP).

The more I think about it, the more I think this is needed at a table-level rather than schema-level.

How about something like:
1. Use information_schema to get the set of all tables
2. Apply any obvious filtering if needed.
3. Use a configurable drop filter to restrict the set of tables: a list of regular expressions that match `<schema>.<table>` names.

**Comment by nassibnassar** [comment]
1. Use information_schema to get the set of all tables, applying any obvious filtering if needed as part of the SQL query.
2. Use a configurable drop filter to restrict the set of tables: a list of regular expressions that match `<schema>.<table>` names.

**Comment by MikeTaylor** [comment]
I don't understand what it would mean "to add locally-created schemas (not created by LDP)". How can a client use a schema that the server does not provide?

**Comment by MikeTaylor** [comment]
Also, in #1, "Use information_schema to get the set of all tables, applying any obvious filtering if needed as part of the SQL query", how would I know what "obvious" filtering is needed?

**Comment by nassibnassar** [comment]
"Obvious" was not the right word on my part.  I meant sort of non-controversial.  I think something like this would do it:
```
select table_schema, table_name
    from information_schema.tables
    where table_schema not in ('dbconfig', 'dbsystem', 'history', 'information_schema', 'pg_catalog')
        and table_name not like '%\_\_';
```

**Comment by nassibnassar** [comment]
> I don't understand what it would mean "to add locally-created schemas (not created by LDP)". How can a client use a schema that the server does not provide?

Users have permissions to create their own tables, by default in the `local` schema but potentially in other schemas that the system administrator creates for them.  Typically these tables are derived from the LDP-created tables.  Does that answer your question?

**Comment by MikeTaylor** [comment]
Well, I have to admit I am still not 100% clear on this one.
1. From reading the mod-ldp code, it seem that the query is just `SELECT t FROM TableObj t WHERE t.tableSchema = 'local' OR t.tableSchema = 'folio_reporting' OR t.tableSchema = 'public' ORDER by t.tableSchema`. The responses to this never include any of the four tables you mentioned, so I guess no pre-filtering is necessary?
2. When users "create their own tables", they will be included in the lists returned from the existing query, right? So I don't need to do anything clever to include them?

**Comment by nassibnassar** [comment]
1. Maybe I am missing something, but the current query in mod-ldp lists specific schemas to be included, while the new query I proposed instead lists schemas to be excluded.
2. I think the new proposed query allows user-created tables by not excluding them.

**Comment by MikeTaylor** [comment]
1. D'oh! Once again, my mind was drifting between schemas and tables. Yes, it constrains the set of schemas to furnish. It doesn't constrain the tables, which is what I was thinking about. OK, I've got it now!
2. Good.
