### ISSUE TITLE
Show consistent product name in top left corner 

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#23]
For consistency of the product name shown in the top left corner:  If possible show FOLIO or ReShare, depending where this app is running, instead of LDP.  If not possible, provide a way to configure the name that is shown.

**Comment by MikeTaylor** [comment]
I believe this is incorrect. All FOLIO apps display their own name when selected, not that of FOLIO (or ReShare) itself. Compare with e.g.:
![Screen Shot 2021-04-08 at 16 34 33](https://user-images.githubusercontent.com/212761/114055083-568d3100-9888-11eb-94c5-e52ad674c48a.png)

**Comment by nassibnassar** [comment]
You are quite right.  So this looks like a "wontfix".
