### ISSUE TITLE
update deps for @folio/stripes v6 compatibility

### ISSUE THREAD

**Issue by zburke** [library-data-platform/ui-ldp#29]
Update deps for compatibility with `@folio/stripes` `^6.0.0` and the peer-deps it expects:

*    "react-redux": "~7.2.0",
*    "redux": "~4.0.0"
*    "react": "^16.8.6",
*    "react-dom": "^16.8.6"

**Comment by MikeTaylor** [comment]
Fixed in PR #30, many thanks @zburke!
