### ISSUE TITLE
Disable log viewer

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#4]
In the spirit of disabling non-critical features not currently maintained, it would be good to disable the log viewer, and update the readme and any other documentation to reflect this.

**Comment by rjruizes** [comment]
Done. [Disabled Log Viewer page](https://github.com/library-data-platform/ui-ldp/blob/3bbbbda79a04a09159b0aa61f3652a9bcf07a76e/src/index.js#L42) and updated [README](https://github.com/library-data-platform/ui-ldp/blob/master/README.md).
