### ISSUE TITLE
prefer @folio/stripes exports to private paths when importing components

### ISSUE THREAD

**Issue by zburke** [library-data-platform/ui-ldp#44]
*Overview:* component imports should happen through the `@folio/stripes/${repo}` namespace rather than directly via the repo's private path. e.g. prefer 
```
import LocationSelection from '@folio/stripes/smart-components/LocationSelection';
```
instead of 
```
import LocationSelection from '@folio/stripes-smart-components/lib/LocationSelection';
```
The following files contain incorrect imports:
```
./ui-ldp/src/index.js:7:import { Loading, NavList, NavListItem, NavListSection, Paneset, Pane } from '@folio/stripes-components';
./ui-ldp/src/components/QueryBuilder/QuerySingleTable.js:8:import exportToCsv from '@folio/stripes-components/lib/ExportCsv/exportToCsv';
./ui-ldp/src/components/QueryBuilder/BigError.js:3:import { Button, Headline, Icon } from '@folio/stripes-components';
./ui-ldp/src/routes/LogsRoute.js:4:import { Datepicker, MultiColumnList, Row, Col } from '@folio/stripes-components';
```

**Comment by MikeTaylor** [comment]
Thanks for spotting this! I'll do it as part of the 1.3 milestone.

(Do you know _why_ this style is considered better, BTW?)

**Comment by zburke** [comment]
> (Do you know why this style is considered better, BTW?)

`ui-ldp` doesn't depend on `@folio/stripes-components`, it depends on `@folio/stripes`. It so happens that the former includes the latter, so this import luckily happens to work, but that's a loophole, not a feature. 

And as to why we should depend on formal exports from a package's top-level, e.g.
```
import { Thing } from '@folio/stripes/components';
```
instead of 
```
import Thing from '@folio/stripes-components/lib/Thing';
```
The former uses the declared public interface for the module. Using the direct path accesses package internals that were never deliberately published for public consumption.

**Comment by MikeTaylor** [comment]
Thanks, @zburke, all of this makes perfect sense.

It looks like there is presently no alternative to
```
import exportToCsv from '@folio/stripes-components/lib/ExportCsv/exportToCsv';
```
though, unless you know different? Certainly the only mentions of `exportToCsv` in stripes-components itself come inside `lib/ExportCsv`.

(In time maybe I will refactor to use the `<ExportCsv>` component instead, but that feels like a separate job.)

**Comment by MikeTaylor** [comment]
I filed the `<ExportCsv>` job as #45.

**Comment by MikeTaylor** [comment]
Ha. Thank you for doing my work for me!
