### ISSUE TITLE
Use case-insensitive pattern matching by default for varchar attributes

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#6]
For varchar fields, we should probably use pattern matching and case-insensitivity by default in this app.  (We can add checkboxes later for "exact" and/or "case sensitive" matching.)

At the moment it looks like we are probably matching a (varchar) filter column `C` on value `'V'` as
```
C = 'V'
```
To implement case-insensitive pattern matching, this might work:
```
C ILIKE '%V%'
```
Note that `ILIKE` is a Postgres/Redshift extension, not standard SQL.

Boolean, numeric and date fields should not be changed.

**Comment by rjruizes** [comment]
Done [here](https://github.com/library-data-platform/mod-ldp/commit/47e56f9c8f3d60b911727049992a897a2ad4631d).
