### ISSUE TITLE
Preserve previous results while editing filter criteria

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#7]
When the filter criteria are edited after a query, any previous results are immediately cleared.  This seems logical, but in practice it could be very useful to refer to the results while editing the filter criteria.  Would it make sense to preserve them until the Submit button is pressed again?

**Comment by rjruizes** [comment]
Removed [here](https://github.com/library-data-platform/ui-ldp/commit/00fc543258c4f24b525c4fbef86f7adcdc406929)
